replicaCount:
  frontend: 1
  backend: 1

images:
  frontend:
    repository: ayyandar/three-tier-frontend
    tag: "dev"
    pullPolicy: Always

  backend:
    repository: ayyandar/three-tier-backend
    tag: "dev"
    pullPolicy: Always

  database:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: Always