replicaCount:
  frontend: 1
  backend: 1
images:
  frontend:
    repository: ayyandar/three-tier-frontend
    tag: "b410b7"
    pullPolicy: Always
  backend:
    repository: ayyandar/three-tier-backend
    tag: "b410b7"
    pullPolicy: Always
  database:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: Always
