apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      automountServiceAccountToken: false

      containers:
        - name: frontend
          image: ayyandar/three-tier-frontend:latest
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 80
              name: http

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20